---
- hosts: prometheus
  remote_user: ubuntu
  become: yes 
  tasks: 
    - name: Install wget latest version 
      apt: 
        name: wget
        state: present 
        update_cache: yes
    - name: Delete Older Files 
      shell: "sudo rm -rf /home/ubuntu/* /usr/local/bin/* /etc/prometheus/* /var/lib/prometheus;"
    - name: Download Promtheus Binary from Source prometheus-2.35.0-rc0.linux-386.tar.gz 
      get_url: 
       url: https://github.com/prometheus/prometheus/releases/download/v2.35.0-rc0/prometheus-2.35.0-rc0.linux-386.tar.gz
       dest: /home/ubuntu/
       checksum: sha256:fba14c913a32e98fed75e8109c50f0904abe679dfae864e4bb10b58ec64fd3e9
    - name: Uncompress File 
      shell: "tar xvzf prometheus-2.35.0-rc0.linux-386.tar.gz; mv prometheus-2.35.0-rc0.linux-386 prometheus-files; chown -R ubuntu:ubuntu prometheus-files "
    - name: Create Prometheus System User 
      shell: "userdel prometheus && useradd --no-create-home '--shell' /usr/sbin/nologin prometheus" 
      #shell: "useradd --no-create-home '--shell' /bin/false prometheus"
    - name: Create Node-Exporter User  
      shell: "userdel node-exporter && useradd --no-create-home '--shell' /usr/sbin/nologin node-exporter"
      #shell: "useradd --no-create-home '--shell' /bin/false node-exporter"
    - name: Update Prometheus User
      shell: "mkdir -p /etc/prometheus; 
              chown -R prometheus:prometheus /etc/prometheus; 
              mkdir -p /var/lib/prometheus;
              chown -R prometheus:prometheus /var/lib/prometheus"
    - name: Copy Prometheus Binary files
      shell: "cp /home/ubuntu/prometheus-files/prometheus /usr/local/bin/; 
              cp /home/ubuntu/prometheus-files/promtool /usr/local/bin/; 
              chown -R prometheus:prometheus /usr/local/bin/prometheus; 
              chmod -R 777 /usr/local/bin/prometheus /usr/local/bin/promtool;
              chown -R prometheus:prometheus /usr/local/bin/promtool"
    - name: Copy Prometheus Console Libraries
      shell: "cp -r /home/ubuntu/prometheus-files/consoles /etc/prometheus; 
              cp -r /home/ubuntu/prometheus-files/console_libraries /etc/prometheus; 
              cp -r /home/ubuntu/prometheus-files/prometheus.yml /etc/prometheus;
              chown -R prometheus:prometheus /etc/prometheus/consoles;
              chown -R prometheus:prometheus /etc/prometheus/console_libraries;
              chown -R prometheus:prometheus /etc/prometheus/prometheus.yml"
    - name: Add Prometheus.service file to Systemd 
      copy:
        src: prometheus.service
        dest: /etc/systemd/system/
    - name: Assign permission 
      shell: "sudo -u prometheus /usr/local/bin/prometheus \ 
             --config.file=/etc/prometheus/prometheus.yml \ 
             --storage.tsdb.path=/var/lib/prometheus/ \ 
             --web.console.templates=/etc/prometheus/consoles \ 
             --web.console.libraries=/etc/prometheus/console_libraries &" 

    # - name: Run Prometheus
    #   shell: "sudo systemctl daemon-reload; sudo systemctl start prometheus; sudo systemctl enable prometheus; sudo systemctl status prometheus"

    # - name: Check if prometheus UP
    #   shell: "curl -IL http://3.109.176.69:9090"