# This Ansible Script will Install Mysqld Exporter 
# https://github.com/prometheus/mysqld_exporter/releases/download/v0.14.0/mysqld_exporter-0.14.0.linux-amd64.tar.gz 
---
- hosts: dbserver
  remote_user: ubuntu
  become: yes 
  tasks: 
    - name: Delete Older Files 
      shell: "sudo rm -rf /home/ubuntu/mysqld_exporter-* /usr/local/bin/mysqld_exporter* "

    - name: Download Mysql exporter 
      get_url:
       url: https://github.com/prometheus/mysqld_exporter/releases/download/v0.14.0/mysqld_exporter-0.14.0.linux-amd64.tar.gz
       dest: /home/ubuntu/
    
    # - name: Create prometheus Group 
    #   group: 
    #     name: prometheus
    #     state: present 
    
    # - name: Create prometheus User 
    #   user: 
    #     name: prometheus
    #     group: prometheus
    #     shell: /usr/sbin/nologin 
    #     create_home: no 
    #     state: present  
    
    - name: Uncompress File 
      shell: "tar xvzf mysqld_exporter-0.14.0.linux-amd64.tar.gz; mv mysqld_exporter-0.14.0.linux-amd64/mysqld_exporter /usr/local/bin/ "
    
    - name: Create mysqld_exporter Service File 
      copy:
        src: /Users/ashwanikishor/Projects/Ansible/prometheus/service/mysqld_exporter.service
        dest: /etc/systemd/system/
 
    # - name: Create Prometheus exporter database user
    #   mysql_user: 
    #     name: mysqld_exporter
    #     password: 'exporter@123'
    #     login_user: root 
    #     login_password: Yq9wyxM#+C
    #     host: localhost
    #     priv: '*.*:ALL'
    #     state: present
  
    - name: Restart mysqld_Exporter Service 
      systemd: 
        daemon_reload: yes
        name: mysqld_exporter.service
        enabled: yes
        state: restarted